In [122]:
#Importando bibliotecas

import pandas as pd

In [123]:
#Criando dataframe

df_players = pd.read_excel("UEFA Champions League 2016-2022 Data.xlsx", sheet_name="players")
display(df_players)

,PLAYER_ID,FIRST_NAME,LAST_NAME,NATIONALITY,DOB,TEAM,JERSEY_NUMBER,POSITION,HEIGHT,WEIGHT,FOOT
0,ply510,NaN,Danilo,Brazil,1991-07-15,Juventus,6.0,Defender,184.0,78.0,R
1,ply511,Mattia De,Sciglio,Italy,1992-10-20,Juventus,2.0,Defender,182.0,78.0,R
2,ply512,Federico,Gatti,Italy,1998-06-24,Juventus,15.0,Defender,190.0,84.0,R
3,ply513,Daniele,Rugani,Italy,1994-07-29,Juventus,24.0,Defender,190.0,84.0,R
4,ply514,Enzo,Barrenechea,Argentina,2001-05-22,Juventus,45.0,Midfielder,186.0,81.0,L
...,...,...,...,...,...,...,...,...,...,...,...
2764,ply2765,Mario,Lemina,Gabon,1993-09-01,NaN,99.0,Midfielder,184.0,84.0,R
2765,ply2766,Marko,Pjaca,Croatia,1995-05-06,NaN,14.0,Forward,186.0,82.0,R
2766,ply2767,Stevan,Jovetić,Montenegro,1989-11-02,NaN,19.0,Forward,183.0,79.0,R
2767,ply2768,Erik,Durm,Germany,1992-05-12,NaN,37.0,Defender,182.0,70.0,R
2768,ply2769,Giorgio,Chiellini,Italy,1984-08-14,NaN,14.0,Defender,187.0,85.0,L

In [124]:
#Criando dataframe

df_matches = pd.read_excel("UEFA Champions League 2016-2022 Data.xlsx", sheet_name="matches")
display(df_matches)

,MATCH_ID,SEASON,DATE_TIME,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,PENALTY_SHOOT_OUT,ATTENDANCE
0,mt1,2021-2022,15-SEP-21 08.00.00.000000000 PM,Manchester City,RB Leipzig,Etihad Stadium,6,3,0,38062
1,mt2,2021-2022,15-SEP-21 08.00.00.000000000 PM,Club Brugge KV,Paris Saint-Germain,Jan Breydel Stadion,1,1,0,27546
2,mt3,2021-2022,28-SEP-21 08.00.00.000000000 PM,Paris Saint-Germain,Manchester City,Parc des Princes,2,0,0,37350
3,mt4,2021-2022,28-SEP-21 08.00.00.000000000 PM,RB Leipzig,Club Brugge KV,Red Bull Arena,1,2,0,23500
4,mt5,2021-2022,19-OCT-21 05.45.00.000000000 PM,Club Brugge KV,Manchester City,Jan Breydel Stadion,1,5,0,24915
...,...,...,...,...,...,...,...,...,...,...
739,mt740,2016-2017,02-MAY-17 07.45.00.000000000 PM,Real Madrid,Atlético Madrid,Santiago Bernabéu,3,0,0,77609
740,mt741,2016-2017,03-MAY-17 07.45.00.000000000 PM,AS Monaco,Juventus,Stade Louis II,0,2,0,16762
741,mt742,2016-2017,09-MAY-17 07.45.00.000000000 PM,Juventus,AS Monaco,Allianz Stadium,2,1,0,40244
742,mt743,2016-2017,10-MAY-17 07.45.00.000000000 PM,Atlético Madrid,Real Madrid,Vicente Calderón,2,1,0,53422
743,mt744,2016-2017,03-JUN-17 07.45.00.000000000 PM,Juventus,Real Madrid,Millennium,1,4,0,65842

In [125]:
#Criando dataframe

df_goals = pd.read_excel("UEFA Champions League 2016-2022 Data.xlsx", sheet_name="goals")
display(df_goals)

     GOAL_ID MATCH_ID      PID  DURATION   ASSIST          GOAL_DESC
0      gl470    mt154  ply1479         4   ply864  right-footed shot
1      gl471    mt154  ply1075        28   ply864            penalty
2      gl472    mt154   ply585        69   ply864  right-footed shot
3      gl473    mt155   ply396        12   ply653  right-footed shot
4      gl474    mt155  ply1064        81   ply653  right-footed shot
...      ...      ...      ...       ...      ...                ...
2274  gl2275    mt744   ply699        20   ply818  right-footed shot
2275  gl2276    mt744      NaN        27  ply1869       bicycle kick
2276  gl2277    mt744   ply690        61      NaN  right-footed shot
2277  gl2278    mt744   ply699        64   ply828  right-footed shot
2278  gl2279    mt744   ply834        90  ply1371   left-footed shot

[2279 rows x 6 columns]

In [126]:
#Renomeando a coluna "PID"

df_goals.rename(columns = {'PID':'PLAYER_ID'}, inplace=True)
display(df_goals)

     GOAL_ID MATCH_ID PLAYER_ID  DURATION   ASSIST          GOAL_DESC
0      gl470    mt154   ply1479         4   ply864  right-footed shot
1      gl471    mt154   ply1075        28   ply864            penalty
2      gl472    mt154    ply585        69   ply864  right-footed shot
3      gl473    mt155    ply396        12   ply653  right-footed shot
4      gl474    mt155   ply1064        81   ply653  right-footed shot
...      ...      ...       ...       ...      ...                ...
2274  gl2275    mt744    ply699        20   ply818  right-footed shot
2275  gl2276    mt744       NaN        27  ply1869       bicycle kick
2276  gl2277    mt744    ply690        61      NaN  right-footed shot
2277  gl2278    mt744    ply699        64   ply828  right-footed shot
2278  gl2279    mt744    ply834        90  ply1371   left-footed shot

[2279 rows x 6 columns]

In [127]:
#Excluindo colunas do dataframe df_players

df_players.drop(['NATIONALITY', 'DOB', 'JERSEY_NUMBER'], axis = 1, inplace=True)
display(df_players)

,PLAYER_ID,FIRST_NAME,LAST_NAME,TEAM,POSITION,HEIGHT,WEIGHT,FOOT
0,ply510,NaN,Danilo,Juventus,Defender,184.0,78.0,R
1,ply511,Mattia De,Sciglio,Juventus,Defender,182.0,78.0,R
2,ply512,Federico,Gatti,Juventus,Defender,190.0,84.0,R
3,ply513,Daniele,Rugani,Juventus,Defender,190.0,84.0,R
4,ply514,Enzo,Barrenechea,Juventus,Midfielder,186.0,81.0,L
...,...,...,...,...,...,...,...,...
2764,ply2765,Mario,Lemina,NaN,Midfielder,184.0,84.0,R
2765,ply2766,Marko,Pjaca,NaN,Forward,186.0,82.0,R
2766,ply2767,Stevan,Jovetić,NaN,Forward,183.0,79.0,R
2767,ply2768,Erik,Durm,NaN,Defender,182.0,70.0,R
2768,ply2769,Giorgio,Chiellini,NaN,Defender,187.0,85.0,L

In [128]:
#Excluindo colunas do dataframe df_matches

df_matches.drop(['DATE_TIME', 'PENALTY_SHOOT_OUT'], axis = 1, inplace=True)
display(df_matches)

,MATCH_ID,SEASON,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,ATTENDANCE
0,mt1,2021-2022,Manchester City,RB Leipzig,Etihad Stadium,6,3,38062
1,mt2,2021-2022,Club Brugge KV,Paris Saint-Germain,Jan Breydel Stadion,1,1,27546
2,mt3,2021-2022,Paris Saint-Germain,Manchester City,Parc des Princes,2,0,37350
3,mt4,2021-2022,RB Leipzig,Club Brugge KV,Red Bull Arena,1,2,23500
4,mt5,2021-2022,Club Brugge KV,Manchester City,Jan Breydel Stadion,1,5,24915
...,...,...,...,...,...,...,...,...
739,mt740,2016-2017,Real Madrid,Atlético Madrid,Santiago Bernabéu,3,0,77609
740,mt741,2016-2017,AS Monaco,Juventus,Stade Louis II,0,2,16762
741,mt742,2016-2017,Juventus,AS Monaco,Allianz Stadium,2,1,40244
742,mt743,2016-2017,Atlético Madrid,Real Madrid,Vicente Calderón,2,1,53422
743,mt744,2016-2017,Juventus,Real Madrid,Millennium,1,4,65842

In [129]:
#Juntado dataframes com merge

df_goals_matches = pd.merge(df_goals, df_matches, how = 'inner', on = 'MATCH_ID')
"""display(df_goals_matches)"""
df_full = pd.merge(df_goals_matches, df_players, how = 'inner', on = 'PLAYER_ID')
display(df_full)

,GOAL_ID,MATCH_ID,PLAYER_ID,DURATION,ASSIST,GOAL_DESC,SEASON,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,ATTENDANCE,FIRST_NAME,LAST_NAME,TEAM,POSITION,HEIGHT,WEIGHT,FOOT
0,gl470,mt154,ply1479,4,ply864,right-footed shot,2020-2021,FC Porto,Olympique Marseille,Estádio do Dragão,3,0,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R
1,gl678,mt224,ply1479,46,ply415,left-footed shot,2020-2021,FC Porto,Juventus,Estádio do Dragão,2,1,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R
2,gl1239,mt409,ply1479,49,ply844,header,2018-2019,FC Porto,Galatasaray,Estádio do Dragão,1,0,42711,Moussa,Marega,NaN,Arabia,183.0,83.0,R
3,gl1240,mt410,ply1479,26,ply94,penalty,2018-2019,Lokomotiv Moskva,FC Porto,RŽD-Arena,1,3,16034,Moussa,Marega,NaN,Arabia,183.0,83.0,R
4,gl1245,mt412,ply1479,43,ply1466,right-footed shot,2018-2019,FC Porto,Lokomotiv Moskva,Estádio do Dragão,4,1,34616,Moussa,Marega,NaN,Arabia,183.0,83.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,gl2207,mt722,ply2766,72,NaN,right-footed shot,2016-2017,FC Porto,Juventus,Estádio do Dragão,0,2,49229,Marko,Pjaca,NaN,Forward,186.0,82.0,R
2172,gl2211,mt723,ply2672,73,NaN,right-footed shot,2016-2017,Sevilla FC,Leicester City,Ramón Sánchez Pizjuán,2,1,38834,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R
2173,gl2253,mt736,ply2672,61,NaN,right-footed shot,2016-2017,Leicester City,Atlético Madrid,King Power Stadium,1,1,31548,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R
2174,gl2232,mt727,ply392,90,ply741,right-footed shot,2016-2017,FC Barcelona,Paris Saint-Germain,Spotify Camp Nou,6,1,96290,Sergi,Roberto,FC Barcelona,Midfielder,178.0,68.0,R
2175,gl2242,mt732,ply2769,55,ply1076,header,2016-2017,Juventus,FC Barcelona,Allianz Stadium,3,0,41092,Giorgio,Chiellini,NaN,Defender,187.0,85.0,L

In [130]:
#Excluindo colunas do dataframe df_full

df_full.drop(['GOAL_ID', 'MATCH_ID', 'PLAYER_ID'], axis = 1, inplace=True)
display(df_full)

,DURATION,ASSIST,GOAL_DESC,SEASON,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,ATTENDANCE,FIRST_NAME,LAST_NAME,TEAM,POSITION,HEIGHT,WEIGHT,FOOT
0,4,ply864,right-footed shot,2020-2021,FC Porto,Olympique Marseille,Estádio do Dragão,3,0,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R
1,46,ply415,left-footed shot,2020-2021,FC Porto,Juventus,Estádio do Dragão,2,1,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R
2,49,ply844,header,2018-2019,FC Porto,Galatasaray,Estádio do Dragão,1,0,42711,Moussa,Marega,NaN,Arabia,183.0,83.0,R
3,26,ply94,penalty,2018-2019,Lokomotiv Moskva,FC Porto,RŽD-Arena,1,3,16034,Moussa,Marega,NaN,Arabia,183.0,83.0,R
4,43,ply1466,right-footed shot,2018-2019,FC Porto,Lokomotiv Moskva,Estádio do Dragão,4,1,34616,Moussa,Marega,NaN,Arabia,183.0,83.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,72,NaN,right-footed shot,2016-2017,FC Porto,Juventus,Estádio do Dragão,0,2,49229,Marko,Pjaca,NaN,Forward,186.0,82.0,R
2172,73,NaN,right-footed shot,2016-2017,Sevilla FC,Leicester City,Ramón Sánchez Pizjuán,2,1,38834,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R
2173,61,NaN,right-footed shot,2016-2017,Leicester City,Atlético Madrid,King Power Stadium,1,1,31548,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R
2174,90,ply741,right-footed shot,2016-2017,FC Barcelona,Paris Saint-Germain,Spotify Camp Nou,6,1,96290,Sergi,Roberto,FC Barcelona,Midfielder,178.0,68.0,R
2175,55,ply1076,header,2016-2017,Juventus,FC Barcelona,Allianz Stadium,3,0,41092,Giorgio,Chiellini,NaN,Defender,187.0,85.0,L

In [131]:
#Concatenando colunas "FIRST_NAME" e "LAST_NAME"

df_full['MARCADOR'] = df_full['FIRST_NAME'].map(str) + ' ' + df_full['LAST_NAME'].map(str)
display(df_full)

,DURATION,ASSIST,GOAL_DESC,SEASON,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,ATTENDANCE,FIRST_NAME,LAST_NAME,TEAM,POSITION,HEIGHT,WEIGHT,FOOT,MARCADOR
0,4,ply864,right-footed shot,2020-2021,FC Porto,Olympique Marseille,Estádio do Dragão,3,0,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R,Moussa Marega
1,46,ply415,left-footed shot,2020-2021,FC Porto,Juventus,Estádio do Dragão,2,1,0,Moussa,Marega,NaN,Arabia,183.0,83.0,R,Moussa Marega
2,49,ply844,header,2018-2019,FC Porto,Galatasaray,Estádio do Dragão,1,0,42711,Moussa,Marega,NaN,Arabia,183.0,83.0,R,Moussa Marega
3,26,ply94,penalty,2018-2019,Lokomotiv Moskva,FC Porto,RŽD-Arena,1,3,16034,Moussa,Marega,NaN,Arabia,183.0,83.0,R,Moussa Marega
4,43,ply1466,right-footed shot,2018-2019,FC Porto,Lokomotiv Moskva,Estádio do Dragão,4,1,34616,Moussa,Marega,NaN,Arabia,183.0,83.0,R,Moussa Marega
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,72,NaN,right-footed shot,2016-2017,FC Porto,Juventus,Estádio do Dragão,0,2,49229,Marko,Pjaca,NaN,Forward,186.0,82.0,R,Marko Pjaca
2172,73,NaN,right-footed shot,2016-2017,Sevilla FC,Leicester City,Ramón Sánchez Pizjuán,2,1,38834,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R,Jamie Vardy
2173,61,NaN,right-footed shot,2016-2017,Leicester City,Atlético Madrid,King Power Stadium,1,1,31548,Jamie,Vardy,Leicester City,Forward,179.0,76.0,R,Jamie Vardy
2174,90,ply741,right-footed shot,2016-2017,FC Barcelona,Paris Saint-Germain,Spotify Camp Nou,6,1,96290,Sergi,Roberto,FC Barcelona,Midfielder,178.0,68.0,R,Sergi Roberto
2175,55,ply1076,header,2016-2017,Juventus,FC Barcelona,Allianz Stadium,3,0,41092,Giorgio,Chiellini,NaN,Defender,187.0,85.0,L,Giorgio Chiellini

In [132]:
#Excluindo colunas "FIRST_NAME" e "LAST_NAME"

df_full.drop(['FIRST_NAME', 'LAST_NAME'], axis = 1, inplace=True)
display(df_full)

,DURATION,ASSIST,GOAL_DESC,SEASON,HOME_TEAM,AWAY_TEAM,STADIUM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,ATTENDANCE,TEAM,POSITION,HEIGHT,WEIGHT,FOOT,MARCADOR
0,4,ply864,right-footed shot,2020-2021,FC Porto,Olympique Marseille,Estádio do Dragão,3,0,0,NaN,Arabia,183.0,83.0,R,Moussa Marega
1,46,ply415,left-footed shot,2020-2021,FC Porto,Juventus,Estádio do Dragão,2,1,0,NaN,Arabia,183.0,83.0,R,Moussa Marega
2,49,ply844,header,2018-2019,FC Porto,Galatasaray,Estádio do Dragão,1,0,42711,NaN,Arabia,183.0,83.0,R,Moussa Marega
3,26,ply94,penalty,2018-2019,Lokomotiv Moskva,FC Porto,RŽD-Arena,1,3,16034,NaN,Arabia,183.0,83.0,R,Moussa Marega
4,43,ply1466,right-footed shot,2018-2019,FC Porto,Lokomotiv Moskva,Estádio do Dragão,4,1,34616,NaN,Arabia,183.0,83.0,R,Moussa Marega
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,72,NaN,right-footed shot,2016-2017,FC Porto,Juventus,Estádio do Dragão,0,2,49229,NaN,Forward,186.0,82.0,R,Marko Pjaca
2172,73,NaN,right-footed shot,2016-2017,Sevilla FC,Leicester City,Ramón Sánchez Pizjuán,2,1,38834,Leicester City,Forward,179.0,76.0,R,Jamie Vardy
2173,61,NaN,right-footed shot,2016-2017,Leicester City,Atlético Madrid,King Power Stadium,1,1,31548,Leicester City,Forward,179.0,76.0,R,Jamie Vardy
2174,90,ply741,right-footed shot,2016-2017,FC Barcelona,Paris Saint-Germain,Spotify Camp Nou,6,1,96290,FC Barcelona,Midfielder,178.0,68.0,R,Sergi Roberto
2175,55,ply1076,header,2016-2017,Juventus,FC Barcelona,Allianz Stadium,3,0,41092,NaN,Defender,187.0,85.0,L,Giorgio Chiellini

In [133]:
df_full = df_full[['SEASON', 'HOME_TEAM', 'AWAY_TEAM', 'HOME_TEAM_SCORE', 'AWAY_TEAM_SCORE', 'MARCADOR', 'DURATION', 'POSITION', 'GOAL_DESC','STADIUM', 'ATTENDANCE']]
display(df_full)

,SEASON,HOME_TEAM,AWAY_TEAM,HOME_TEAM_SCORE,AWAY_TEAM_SCORE,MARCADOR,DURATION,POSITION,GOAL_DESC,STADIUM,ATTENDANCE
0,2020-2021,FC Porto,Olympique Marseille,3,0,Moussa Marega,4,Arabia,right-footed shot,Estádio do Dragão,0
1,2020-2021,FC Porto,Juventus,2,1,Moussa Marega,46,Arabia,left-footed shot,Estádio do Dragão,0
2,2018-2019,FC Porto,Galatasaray,1,0,Moussa Marega,49,Arabia,header,Estádio do Dragão,42711
3,2018-2019,Lokomotiv Moskva,FC Porto,1,3,Moussa Marega,26,Arabia,penalty,RŽD-Arena,16034
4,2018-2019,FC Porto,Lokomotiv Moskva,4,1,Moussa Marega,43,Arabia,right-footed shot,Estádio do Dragão,34616
...,...,...,...,...,...,...,...,...,...,...,...
2171,2016-2017,FC Porto,Juventus,0,2,Marko Pjaca,72,Forward,right-footed shot,Estádio do Dragão,49229
2172,2016-2017,Sevilla FC,Leicester City,2,1,Jamie Vardy,73,Forward,right-footed shot,Ramón Sánchez Pizjuán,38834
2173,2016-2017,Leicester City,Atlético Madrid,1,1,Jamie Vardy,61,Forward,right-footed shot,King Power Stadium,31548
2174,2016-2017,FC Barcelona,Paris Saint-Germain,6,1,Sergi Roberto,90,Midfielder,right-footed shot,Spotify Camp Nou,96290
2175,2016-2017,Juventus,FC Barcelona,3,0,Giorgio Chiellini,55,Defender,header,Allianz Stadium,41092

In [134]:
a = df_full.rename(columns={'SEASON': 'TEMPORADA', 'HOME_TEAM': 'TIME DA CASA', 'AWAY_TEAM': 'TIME CONTRA', 'HOME_TEAM_SCORE': 'PLACAR DO TIME DA CASA', 'AWAY_TEAM_SCORE': 'PLACAR DO TIME CONTRA', 'DURATION': 'TEMPO DO GOL', 'POSITION': 'POSICAO', 'GOAL_DESC': 'TIPO DE GOL', 'STADIUM': 'ESTADIO', 'ATTENDANCE': 'PUBLICO DO JOGO'})

In [135]:
z = a.replace({"free kick": "Gol de Falta","header": "Gol de Cabeça","left-footed shot":"Gol com Perna Esquerda","own goal":"Gol Contra","penalty":"Penalti","right-footed shot":"Gol com Perna Direita", "bicycle kick":"Gol de Bicicleta", "Back Heel":"Gol de Letra","ind. free kick":"Gol Olimpico"})

In [136]:
b = z.replace({"Forward":"Atacante","Defender":"Zagueiro","Goalkeep":"Goleiro","Midfielder":"Meio de Campo","Arabia":"Atacante","Emirates":"Meio de Campo"})

In [137]:
b.head(5)

,TEMPORADA,TIME DA CASA,TIME CONTRA,PLACAR DO TIME DA CASA,PLACAR DO TIME CONTRA,MARCADOR,TEMPO DO GOL,POSICAO,TIPO DE GOL,ESTADIO,PUBLICO DO JOGO
0,2020-2021,FC Porto,Olympique Marseille,3,0,Moussa Marega,4,Atacante,Gol com Perna Direita,Estádio do Dragão,0
1,2020-2021,FC Porto,Juventus,2,1,Moussa Marega,46,Atacante,Gol com Perna Esquerda,Estádio do Dragão,0
2,2018-2019,FC Porto,Galatasaray,1,0,Moussa Marega,49,Atacante,Gol de Cabeça,Estádio do Dragão,42711
3,2018-2019,Lokomotiv Moskva,FC Porto,1,3,Moussa Marega,26,Atacante,Penalti,RŽD-Arena,16034
4,2018-2019,FC Porto,Lokomotiv Moskva,4,1,Moussa Marega,43,Atacante,Gol com Perna Direita,Estádio do Dragão,34616

In [138]:
b.to_excel('Dados_Tratados_UEFA.xlsx', index=True, encoding='utf_8')